import type { Dataset } from "./dataset";

/** Minimal stub dataset. Replace with a complete dataset for accuracy. */
export const STUB_DATASET: Dataset = {
  16: { name: "Wild Horseradish", category: "Forage", basePrice: 50 },
  18: { name: "Daffodil", category: "Forage", basePrice: 30 },
  20: { name: "Leek", category: "Forage", basePrice: 60 },
  22: { name: "Dandelion", category: "Forage", basePrice: 40 },
  24: { name: "Parsnip", category: "Crop", basePrice: 35 },
  78: { name: "Cave Carrot", category: "Forage", basePrice: 25 },
  128: { name: "Pufferfish", category: "Fish", basePrice: 200 },
  129: { name: "Anchovy", category: "Fish", basePrice: 30 },
  131: { name: "Sunfish", category: "Fish", basePrice: 30 },
  136: { name: "Smallmouth Bass", category: "Fish", basePrice: 50 },
  142: { name: "Sardine", category: "Fish", basePrice: 40 },
  145: { name: "Bream", category: "Fish", basePrice: 45 },
  147: { name: "Largemouth Bass", category: "Fish", basePrice: 100 },
  153: { name: "Carp", category: "Fish", basePrice: 30 },
  155: { name: "Catfish", category: "Fish", basePrice: 200 },
  168: { name: "Cranberries", category: "Crop", basePrice: 75 },
  184: { name: "Cheese", category: "Artisan", basePrice: 230 },
  188: { name: "Large Egg (White)", category: "Animal", basePrice: 95 },
  197: { name: "Eggplant Parmesan", category: "Cooking", basePrice: 200 },
  208: { name: "Pale Broth", category: "Cooking", basePrice: 150 },
  212: { name: "Pumpkin Pie", category: "Cooking", basePrice: 385 },
  214: { name: "Glazed Yams", category: "Cooking", basePrice: 200 },
  216: { name: "Plum Pudding", category: "Cooking", basePrice: 260 },
  218: { name: "Artichoke Dip", category: "Cooking", basePrice: 210 },
  219: { name: "Stir Fry", category: "Cooking", basePrice: 335 },
  227: { name: "Fried Mushroom", category: "Cooking", basePrice: 200 },
  228: { name: "Pizza", category: "Cooking", basePrice: 600 },
  232: { name: "Cranberry Sauce", category: "Cooking", basePrice: 350 },
  234: { name: "Bread", category: "Cooking", basePrice: 120 },
  242: { name: "Cheese Cauli.", category: "Cooking", basePrice: 300 },
  253: { name: "Cranberry Candy", category: "Cooking", basePrice: 175 },
  254: { name: "Bruschetta", category: "Cooking", basePrice: 210 },
  259: { name: "Seafoam Pudding", category: "Cooking", basePrice: 300 },
  270: { name: "Pumpkin", category: "Crop", basePrice: 320 },
  271: { name: "Corn", category: "Crop", basePrice: 50 },
  276: { name: "Yam", category: "Crop", basePrice: 160 },
  280: { name: "Wheat", category: "Crop", basePrice: 25 },
  282: { name: "Ancient Fruit", category: "Crop", basePrice: 550 },
  284: { name: "Hops", category: "Crop", basePrice: 25 },
  286: { name: "Pale Ale", category: "Artisan", basePrice: 300 },
  296: { name: "Grape", category: "Crop", basePrice: 80 },
  300: { name: "Amaranth", category: "Crop", basePrice: 150 },
  303: { name: "Wine", category: "Artisan", basePrice: 400 },
  346: { name: "Truffle Oil", category: "Artisan", basePrice: 1065 },
  395: { name: "Cactus Fruit", category: "Forage", basePrice: 75 },
  396: { name: "Coconut", category: "Forage", basePrice: 100 },
  433: { name: "Truffle", category: "Animal", basePrice: 625 },
  591: { name: "Starfruit", category: "Crop", basePrice: 750 },
  613: { name: "Mango", category: "Crop", basePrice: 130 },
  635: { name: "Qi Fruit", category: "Crop", basePrice: 1 },
  682: { name: "Fairy Rose Honey", category: "Artisan", basePrice: 952 },
  688: { name: "Green Tea", category: "Artisan", basePrice: 100 },
  700: { name: "Tomato", category: "Crop", basePrice: 60 },
  702: { name: "Hot Pepper", category: "Crop", basePrice: 40 },
  706: { name: "Blueberry", category: "Crop", basePrice: 50 },
  708: { name: "Melon", category: "Crop", basePrice: 250 },
  709: { name: "Radish", category: "Crop", basePrice: 90 },
  715: { name: "Pomegranate", category: "Fruit", basePrice: 140 }
};
